version: '3.4'

services:
  monitora-ai:
    image: monitora-ai
    build: .
      #context: .
      #dockerfile: ./Dockerfile
    #environment:
    # NODE_ENV: production
    ports:
      - 8081:80